sonar.projectKey=oficina-marimb0ndo
sonar.projectName=Oficina Marimb0ndo API
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=src/**/*.d.ts,src/server.ts,src/infrastructure/database/migrations/**,src/__tests__/**

sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# OWASP Top 10 & security rules are enabled by default in SonarQube's Way quality profile
# Coverage threshold: SonarQube Quality Gate will enforce 80% minimum
sonar.coverage.exclusions=src/**/*.d.ts,src/server.ts,src/infrastructure/database/migrations/**,src/__tests__/**

sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN}
