apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
  namespace: oficina-marimb0ndo
  labels:
    app: oficina-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo "Aguardando PostgreSQL..."; sleep 3; done; echo "PostgreSQL pronto!"']
      containers:
        - name: oficina-api
          image: yaraduarte/oficina-marimb0ndo-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: oficina-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: DB_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: JWT_SECRET
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: SMTP_PASS
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
